[project]
name = "meli"
version = "0.1.0"
description = "Project for the Mercado Livre Fraud model assessment"
readme = "README.md"
authors = [
    { name = "Renato Alves", email = "renato.mar.alves@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "lightgbm>=4.7.0",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
    "xgboost-cpu>=3.4.1",
]

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "pytest>=9.1.1",
]
